name: Hello World Training Workflow

on:
  workflow_dispatch:
  issues:
    types: [opened, edited]

jobs:
  greet:
    runs-on: ubuntu-latest
    env:
            MINHA_VARIAVEL: "João Doe"
    steps:
      - name: Greet the User
        run: echo "Hello World!"
      - name: Run a multi-line script
        run: |
          echo "Hello $MINHA_VARIAVEL"
          echo "Hello $GITHUB_ACTOR"
